### ISSUE TITLE
[suggestion] Clear/View Commands

### ISSUE THREAD

**Issue by Narobic** [Beauver/ExtraTerminalCommands#10]
simple "clear" command to clear the text that sometimes overlays the monitor view

in addition, a simple command "view" that pops up the monitor view (instead of typing out the whole thing)

another suggestion I thought of after I posted this was to add the ability to switch the player view using the arrow keys

**Comment by Beauver** [comment]
The first two commands would probably be easy to do, third one may be challenging, though I'll try my best to add it!

**Comment by Sebiann** [comment]
I'm guessing the third suggestion would be like this mod:
[FastSwitchPlayerViewInRadar](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/)

**Comment by Narobic** [comment]
Oh! Exactly lol

**Comment by Beauver** [comment]
I don't think I will be able to make they keyboard switch thingy, as @Sebiann pointed out, [FastSwitchPlayerViewInRadar](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/) for that exists, if you wish to use that, feel free to!

I have made your clear command, and am working on the view one, although, I haven't found an easy way of doing that one, I'll try my best to figure it out lmao

**Comment by Beauver** [comment]
I am sad to say that after ~6 hours of looking into the view command, I could not figure out how it should work.

Your clear command has been created and you should expect to see it in v1.3.0

Will be closed as not planned since I could only execute 1/3 suggestions

**Comment by Beauver** [comment]
Something that falls into the same category as this; I added a switch abbreviation
