### ISSUE TITLE
AllowLaunch config doesnt work

### ISSUE THREAD

**Issue by Sebiann** [Beauver/ExtraTerminalCommands#11]
When starting a new game, it doesn't allow you to launch on the first day.
MSG: Could not launch to space, you can only launch to a moon.
even though I am in space and want to launch to a moon

Edit: It does work when AllowLaunch is set to true

EDIT:
If AllowLaunch = false, you can never use launch even though you should be able to in space

**Comment by Beauver** [comment]
You can expect your bug to be fixed in V1.3.0
