### ISSUE TITLE
1.3.0 Delayed Typing Bug (and profile pic submission)

### ISSUE THREAD

**Issue by Narobic** [Beauver/ExtraTerminalCommands#12]
Hey! I know you were taking a break from updates, but I noticed that ever since the 1.3.0 update, it delays my typing for a brief second when I first hop on the terminal. So I only type the last half of what I was typing, unless I wait roughly 3 seconds before I start typing.

Also, I made these for you cause you said you didn't like the current icon you have
![ETC 1](https://github.com/Beauver/ExtraTerminalCommands/assets/38475963/f63968e5-9b94-48e2-8b37-a954e807ee1c)
![ETC 2](https://github.com/Beauver/ExtraTerminalCommands/assets/38475963/a6675349-913a-4089-81c7-7d79528d053f)

**Comment by Beauver** [comment]
Hey, no worries, I did specify I would do a bugfix update if that was nessacary, or if there were many suggestions I'd keep updating the mod.
But that's a lot of seconds, I'll check it out if I'm home and see if I can figure it out.

Also the logo looks amazing, thanks, you didn't have to!

**Comment by Narobic** [comment]
Going back and testing again, 3 seconds might be hyperbolic... but it's definitely longer than vanilla. I type pretty quick on the terminal so it feels like forever. 

And don't mention it! I love working photoshop and you're super responsive and awesome with feedback!

**Comment by Beauver** [comment]
Hey there, I have gotten on and tried to replicate your issue and I somewhat see what you mean.
Whenever  going into the terminal it does block you from typing for ~0.5-1s, however, this seems to be a vanilla "feature".

I have tried the following, where the same bug kept reocurring:
- Every mod enabled (see video 1: modded) (mods: ETC, TerminalApi, UnityExplorer (developing mod))
- Disabled my mod (ETC)
- Disabled TerminalAPI
- Disabled BepInEx
- Launched a vanilla instance inside of Thunderstore (see video 2: vanilla)

For me it seems like it's a vanilla "feature". Although, if you want to, you could send some video's through which shows a longer delay when you can start typing and maybe with that I could fix it, if it is an issue with my mod.
In addition, you're not getting any errors whilst starting to type as soon 

as you enter the terminal, right?

> And don't mention it! I love working photoshop and you're super responsive and awesome with feedback!

I'll update the modpack and credit you with the logo in a moment!

https://github.com/Beauver/ExtraTerminalCommands/assets/66181330/e8dda620-c9bd-45c3-9645-81d71623657d

https://github.com/Beauver/ExtraTerminalCommands/assets/66181330/09e03965-187e-4dd0-8421-b8f0d6309125

**Comment by Narobic** [comment]
I see. Well, let me do some more testing on my end and see. Thanks as always!

**Comment by Beauver** [comment]
Did you do some testing? If so, do you know what is happening for you?

**Comment by Beauver** [comment]
As I've not recieved any more information I am assuming everything is fine? Please reopen a new/this issue if this is not the case.
