### ISSUE TITLE
Weather Filter condition broken.

### ISSUE THREAD

**Issue by PseudoCoffee** [Beauver/ExtraTerminalCommands#14]
In RandomMoonCommand at onRandomMoonNoFilter() function among the first few lines you are checking `if(ETCNetworkHandler.Instance.launchCmdDisabled)` instead of `if(ETCNetworkHandler.Instance.allowWeatherFilter)`. I believe this is a bug as you intended to check if the config for weather filter is enabled or not instead of checking if launching from non-moons is possible.

**Comment by Beauver** [comment]
Yeah you're right, I may have messed it up for some reason, why, no idea, I'll publish a fix for this later today, thanks!

However, it should've been ``if(ETCNetworkHandler.Instance.randomCmdDisabled)`` as it's about the random command without any filters. 
Seems like the same issue occured with the weather filter, there it would be ``if(!ETCNetworkHandler.Instance.allowWeatherFilter)``
