### ISSUE TITLE
SW command does not work

### ISSUE THREAD

**Issue by PseudoCoffee** [Beauver/ExtraTerminalCommands#15]
I tried using the new SW V1.4.0, and the switch command does not seem to work even tested with the flag set to true.
Might be some issue with the command not being registered with `AddCommand` and having a dynamic argument for player.

**Comment by Beauver** [comment]
It will say the command doesn't work, this is also in the known bugs area in the readme, which is incorrect. It does work, it should switch to the next person, or mentioned person. I think its a bug that the first time using it you have to run it twice, but unsure about that.

And yes you are right about the AddCommand not being a thing here, I had to make it a possibility to input usernames, which I believe you can't with the AddCommand. I'm currently just reading console input which might be why it doesn't recognize it, I will try and fix this bug when I have time however

**Comment by Beauver** [comment]
I got 50% fixed, it doesn't spam say the error anymore whenever you're writing "sw" or "s", only does it whenever you write "sw [user]" at the moment. I'll see if I can do anything about it

**Comment by Beauver** [comment]
I will have to check out the thing with usernames later this weekend sadly, I don't have that much time for it right now

**Comment by Beauver** [comment]
This should be fixed in v1.4.1 which will be released sometime soon, if a bug occurs with this, please let me know and I will take a look at it
