### ISSUE TITLE
Suggestion: Add Horn & Detailed Scan Command

### ISSUE THREAD

**Issue by SoopCanSam** [Beauver/ExtraTerminalCommands#16]
Not sure if it's possible, but it would be cool to have a command to use the horn on the ship. It could be followed by a number for how long it is used. 

It would also be nice to have the "Detailed Scan" command implemented from this mod: https://github.com/fivetoofive/LethalCompany-DetailedScan

You've made an incredible mod though, great work.

**Comment by Beauver** [comment]
I'll check this out next time whenever I have a little more time on my hands, thanks for the suggestion tho!

**Comment by Beauver** [comment]
I will be releasing the bugfix version first today, after that I will take a look into this suggestion

**Comment by Beauver** [comment]
There are a few things that I am going to change about this:
1. You can only write 'horn' and choose the amount of seconds in the config, specifying how many seconds would be possible, however, the way I would be doing it wouldn't be great for optimalization
2. I most likely wont be doing the detailed scan as I don't want to copy a great plugin already.

**Comment by SoopCanSam** [comment]
Makes sense. It's a great mod either way. So you will not be adding either of these?

**Comment by Beauver** [comment]
> Makes sense. It's a great mod either way. So you will not be adding either of these?

I will be adding the "horn" command somewhere later this week, although I am unsure if I can make it go for a custom amount of seconds ("horn 30" for example).
I can make a config which lets you tweak the time, so if you set that to 20s and you type "horn" the horn will sound for 20s.

I'll try to see if there is a way I can make the horn go for a custom amount of time, but can't promise anything that far

Edit: I suck at markdown

**Comment by SoopCanSam** [comment]
That would be sweet either way honestly. 
Thanks for taking a look at it.

**Comment by Beauver** [comment]
Update will be available soon, I have added a 'horn' and a 'horn [sec]' command.
Values can be tweaked in the configs

**Comment by colorfighter** [comment]
Other mod features are already working.But why isn't the horn function working,doesn't this horn refer to the loud horn?
https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/93b87d59-3ebc-464b-98ac-39cabd2a6545
