### ISSUE TITLE
Random moon function will never pick the last option.

### ISSUE THREAD

**Issue by PseudoCoffee** [Beauver/ExtraTerminalCommands#17]
Due to how the random moon is calculated in `private static string goToRandomPlanet(List<SelectableLevel> moons)` at `int randomMoonNum = rnd.Next(0, moons.Count - 1);` excludes last moon, this is often Titan or the last one with good weather.
According to [microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-8.0#system-random-next(system-int32-system-int32)), Next will include minValue but exclude maxValue thus ignore last moon in the list.
A simple fix would be to change `int randomMoonNum = rnd.Next(0, moons.Count);`.

**Comment by Beauver** [comment]
Casual me being amazing at math, thanks, I'll check it out somewhere tomorrow/Thursday! (It's 0:42am help)

**Comment by Beauver** [comment]
Sorry for doing this a little later, this should be fixed in the next version (1.4.1), hopefully that will release this weekend, depends on how easily I can solve the other bug
