### ISSUE TITLE
Switch command already exists

### ISSUE THREAD

**Issue by exverge-0** [Beauver/ExtraTerminalCommands#18]

**Comment by Beauver** [comment]
Without extra information I can not help. Regardless, this shouldn't be an issue as it's just a warning that the command exists. Nothing else happens, the command doesn't get created again so.

If you want me to patch this with a low priority however, please provide more details like:
- when does it happen (startup or something else)
- what's the entire message (or console picture)
- etc

**Comment by exverge-0** [comment]
I haven’t seen a message in console, I just made this issue because there had already existed a command with the same functionality in the base game, otherwise there isn’t necessarily an issue

**Comment by Beauver** [comment]
> I haven’t seen a message in console, I just made this issue because there had already existed a command with the same functionality in the base game, otherwise there isn’t necessarily an issue

Oh like that, well what command are you trying to run & what command already exists?

**Comment by Hanfos** [comment]
I guess he means "switch" 
When u type the command "view monitor" u see the map view of the player which is chosen on the display and when u type "switch" it switches to the next players map view

![vivaldi_xaeo1P](https://github.com/Beauver/ExtraTerminalCommands/assets/13385833/ae3e1899-9daf-4459-922f-e581dd56a4f4)

**Comment by Beauver** [comment]
Right like that, I see. Several people once asked me if I could abbreviate the switch command, so I did. I never overwrite the "switch" command itself either, I just add 'sw' or 's'

If there are any further questions feel free to open this/another issue
