### ISSUE TITLE
Why is the mod not working

### ISSUE THREAD

**Issue by colorfighter** [Beauver/ExtraTerminalCommands#19]
How do I make the mod work?
![微信截图_20240223044054](https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/b0d9a394-4aa1-41b3-8627-dab538b1c565)
![微信截图_20240223044203](https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/11408cd8-b6eb-4604-895b-6ed9058353b4)

https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/3647cd1a-b535-4352-b3a9-c7cfa3f575e1

**Comment by Beauver** [comment]
The dll file and network handler must be kept in the folder in the right place. This should be automatically be done when you install the mod.

In addition you must have [TerminalAPI](https://thunderstore.io/c/lethal-company/p/NotAtomicBomb/TerminalApi/) installed. If you're using the thunderstore launcher, this should be done automatically, if not you must manually install this

**Comment by colorfighter** [comment]
Other mod features are already working.But why isn't the horn function working,doesn't this horn refer to the loud horn?

https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/cd7e41a2-097a-43f9-86b0-ff21da7d27f1

**Comment by Beauver** [comment]
You're right, it should refer to that, although it's weird that it doesn't work as the "horn" command without any given seconds should sound for the amount of seconds in the configuration file ("SecondsEnabled", default: 10s)

Unless you changed that configuration it's weird, do any errors occur in the console when you run the horn command?

**Comment by colorfighter** [comment]
I didn't change any configuration.As soon as I type [horn],it shows "the horn will continue to sound".But  the horn didn't work.
![微信截图_20240223204928](https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/38ec31aa-e660-48a5-8296-74672b85f9f7)
![微信截图_20240223205719](https://github.com/Beauver/ExtraTerminalCommands/assets/150621437/9b133a2d-fcae-4550-99e8-658a6048f1ea)

**Comment by colorfighter** [comment]
The command worked.
