### ISSUE TITLE
Teleport player by name

### ISSUE THREAD

**Issue by ZachHaber** [Beauver/ExtraTerminalCommands#21]
Could you make the teleport command allow for teleporting a player by their name? e.g. "tp ted" to teleport a player named ted? That way you can do quick rescues without having to switch to the player first!

**Comment by Beauver** [comment]
Thanks for the suggestion, I appreciate it!

Though I do have the unfortunate news that I am unsure if I will even continue working on this mod as this mod was intentionally made for my friends to enjoy, currently we've outgrown lethal and thus am unsure if I'll keep working on it.
There are plenty of other mods that most likely do the same as mine which are being constantly updated, I recommend you may want to try out those

If I ever do update the mod again I'll gladly implement your suggestion!

Thanks for understanding
