### ISSUE TITLE
when I type random, it says I'm already landed on a planet despite being in orbit

### ISSUE THREAD

**Issue by Narobic** [Beauver/ExtraTerminalCommands#6]
title says it all. please help, it's a great mod

**Comment by Beauver** [comment]
Could you check if you can open the doors whilst you are in orbit? My code checks on either two things: Wether you can open the ship, or wether your current planet doesn't have time (this should only be the company planet)

In my experience I haven't had this issue yet, does the same thing happen when you just type in "r" (abbreviation of the random command)?
If so, could you attach an video or describe what you are doing so I can try to recreate the issue, thanks!

**Comment by Narobic** [comment]
all the other commands seem to work as normal. I just went in the config and changed the price for random to 0 and I'm going to see if that helps. I only had 80 credits

**Comment by Beauver** [comment]
Could be the case that you had insufficient credits, although it's weird that it gives you the error of already being on a moon. I'm assuming you got this error?
"You are currently on a moon. Can not travel to a random moon."

**Comment by Narobic** [comment]
Yes, that's the error. I tried changing the price and nothing. The door command successfully recognizes that I'm not on a moon

**Comment by Narobic** [comment]
Oh! It's cause I was in orbit around the company building

**Comment by Beauver** [comment]
> Oh! It's cause I was in orbit around the company building

That's weird too, I believe it should work regardless, I'll try to fix that though, thanks for your report!

**Comment by Narobic** [comment]
no worries! great mod!

**Comment by Beauver** [comment]
> Oh! It's cause I was in orbit around the company building

I think I know what's wrong, as I'm checking "!startOfRound.currentLevel.planetHasTime", which means, if a planet doesn't have time, print the error. I thought this would only be for once you've landed, though I guess it also counts when you're in orbit.
Since the company building doesn't have time, it prints that error. I'll test this to be certain, but hope to get a fix out soon, thanks!

**Comment by Narobic** [comment]
oh, on a separate request, would it be possible to turn off paid planets by default without having to type a modifier?

**Comment by Beauver** [comment]
> oh, on a separate request, would it be possible to turn off paid planets by default without having to type a modifier?

I am currently still working on a way of filtering by price, apperently it wasn't as straightforward as I thought when it came to filtering by price, but I'll take your idea and make it into a config whenever I release a filtering by money!

**Comment by Narobic** [comment]
RouteRandom did that, idk if you wanna reach out to that mod's creator

**Comment by Beauver** [comment]
Should be fixed, if this issue, or another issue because of this occurs, feel free to reopen or create another issue.
I simply removed the check if a planet has time, which seems to be completely fine I think.

You can expect your bug to be fixed in either 1.2.2 or 1.3.0

Regarding your suggestion, I'll make a seperate issue and tag you in it

**Comment by Beauver** [comment]
-Did not get fixed-

**Comment by Beauver** [comment]
> Should be fixed, if this issue, or another issue because of this occurs, feel free to reopen or create another issue. I simply removed the check if a planet has time, which seems to be completely fine I think.
> 
> You can expect your bug to be fixed in either 1.2.2 or 1.3.0
> 
> Regarding your suggestion, I'll make a seperate issue and tag you in it

Seems like the if statement did not get updated, now changed it back to what it should be.
-Should be fixed with my testing-
