### ISSUE TITLE
When loading a save

### ISSUE THREAD

**Issue by BakaTekku** [Beauver/ExtraTerminalCommands#7]
`[Error  : Unity Log] NullReferenceException
Stack trace:
ExtraTerminalCommands.Networking.ETCNetworkHandler.OnNetworkSpawn () (at C:/Users/bvver/OneDrive/Documenten/GitHub/LethalCompanyMods/TerminalShipStart/ExtraTerminalCommands/ExtraTerminalCommands/ExtraTerminalCommands/Networking/ETCNetworkHandler.cs:17)
Unity.Netcode.NetworkBehaviour.VisibleOnNetworkSpawn () (at <895801699cfc4b4ab52267f31e2a4998>:0)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkBehaviour:VisibleOnNetworkSpawn()
Unity.Netcode.NetworkObject:InvokeBehaviourNetworkSpawn()
Unity.Netcode.NetworkSpawnManager:SpawnNetworkObjectLocallyCommon(NetworkObject, UInt64, Boolean, Boolean, UInt64, Boolean)
Unity.Netcode.NetworkSpawnManager:SpawnNetworkObjectLocally(NetworkObject, UInt64, Boolean, Boolean, UInt64, Boolean)
Unity.Netcode.NetworkObject:SpawnInternal(Boolean, UInt64, Boolean)
ExtraTerminalCommands.Networking.NetworkObjectManager:SpawnNetworkHandler() (at C:/Users/bvver/OneDrive/Documenten/GitHub/LethalCompanyMods/TerminalShipStart/ExtraTerminalCommands/ExtraTerminalCommands/ExtraTerminalCommands/Networking/NetworkObjectManager.cs:29)
StartOfRound:DMD<StartOfRound::Awake>(StartOfRound)`

**Comment by Beauver** [comment]
It seems like this is an issue upon loading in the network manager, did this only happen once or does this keep happening?

Could you check the following path and see if the "extraterminalcommandsnetwork" file is there?:
``{LETHAL COMP PATH}/BepInEx/plugins/Beauver-ExtraTerminalCommands/ExtraTerminalCommands/``

You may reach this by going to thunderstore --> selecting your modpack with my mod --> settings --> all --> browse profile folder --> follow the path as given before.

**Comment by BakaTekku** [comment]
it keeps Happening. I checked the path and the file is indeed there.
it only happens when loading a save file.
no errors when launching the game and creating a new save.

I can consistently reproduce the error by
Hosting the lobby
Closing the lobby
on Rehosting old or  new lobby (the error happens here)

**Comment by Beauver** [comment]
> it keeps Happening. I checked the path and the file is indeed there. it only happens when loading a save file. no errors when launching the game and creating a new save.
> 
> I can consistently reproduce the error by Hosting the lobby Closing the lobby on Rehosting old or new lobby (the error happens here)

I'll try to recreate your in more detail bug as soon as possible as it's getting late for me now and I still have school tomorrow ):

Do you know if it fully breaks my mod, like when you run "intro", what happens, does it still play the intro for you, for everyone, or does it just not play? Or does it crash your game completely?

Thank you for your feedback, appreciate it, I'll try looking into it what could cause the issue!

**Comment by Beauver** [comment]
After a while I've figured out how this bug occurs, not yet fixed.

It is when you launch/join a game for the second time, just not the first time. I'll see what I can do to fix this.

**Comment by Beauver** [comment]
Your issue should be fixed whenever V1.3.0 releases, if this is not the case, you may reopen this issue. 

Could not replicate it after I implemented my fix. We may have used different methods as it's not been explained exactly.
