### ISSUE TITLE
Won't let me enter a public server?

### ISSUE THREAD

**Issue by ivjvon** [Beauver/ExtraTerminalCommands#9]
I discovered that this was the only mod that won't let me access public servers. Is it server-sided now?

**Comment by Beauver** [comment]
I have recently added networking to my mod, which requires both the client and the host/server to have the mod installed. 
Before the host would still have to have installed to function, however you could still join others if the host didn't have the mod, it just wouldn't function as far as I was aware.

However, if it sounds like a good idea, I could make a config which allows or dissalows for networking. Meaning, if you disable networking in your config, you should be able to join again public servers. Does this sound like a good idea?

**Comment by ivjvon** [comment]
> I have recently added networking to my mod, which requires both the client and the host/server to have the mod installed. Before the host would still have to have installed to function, however you could still join others if the host didn't have the mod, it just wouldn't function as far as I was aware.
> 
> However, if it sounds like a good idea, I could make a config which allows or dissalows for networking. Meaning, if you disable networking in your config, you should be able to join again public servers. Does this sound like a good idea?

So networking blocks me from going public servers, I think not putting it is a much fit and a better way.

**Comment by Beauver** [comment]
> I think not putting it is a much fit and a better way.

What do you mean with this, my mod or the networking? As I am planning on keeping the networking for the commands such as intro, random. These require networking, like I said, I would be willing to make a config to disable networking, meaning it _should_ let you join public servers again if you change this.

**Comment by ivjvon** [comment]
Maybe it would be a good idea are you going to add lethal config in the requirements?

**Comment by Beauver** [comment]
No, however, if you wish to use lethal config, you can install and use it, this mod is compatible with it, I do not want more dependencies when I don't need them. 
However, you can also edit the configs without lethal config in thunderstore.

**Comment by ivjvon** [comment]
Is the networking option already there?

**Comment by Beauver** [comment]
No. I have been busy with school and other things, I have not been able to make your suggestion into a feature yet. 
I close my issues whenever the feature is made with information when you can expect it to be available.
I expect that your feature will be in V1.3.0 or either V1.4.0

**Comment by ivjvon** [comment]
I see, hope you get to it soon, I love your mod

**Comment by Beauver** [comment]
I am sorry to dissapoint, however after spending a few hours looking for a fix to this, it seems like it isn't possible to add a simple config that disables networking. The UnityNetcodePatcher automatically patches the plugin and requires others to have this mod. There's no way around that other to make a new mod without the patcher installed, which I am currently not expecting to do as V1.3.0 might become my last version (see thunderstore once V1.3.0 has released)
